# Generated by Django 3.1.7 on 2021-05-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210514_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hash_url',
            field=models.CharField(max_length=32, null=True, verbose_name='URL'),
        ),
    ]
