# Generated by Django 3.1.7 on 2021-11-07 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20210717_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='hash_url',
        ),
        migrations.AddField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de registro'),
        ),
    ]
