# Generated by Django 3.1.7 on 2021-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20211107_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='hashid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='hash_url',
            field=models.CharField(max_length=32, null=True, verbose_name='URL'),
        ),
    ]
