# Generated by Django 3.1.7 on 2021-11-08 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20211108_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='hash_url',
        ),
        migrations.AddField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.UUID('b6694f1e-427d-45d7-817b-51b29eaaefa1'), editable=False, unique=True),
        ),
    ]
