# Generated by Django 3.1.7 on 2021-11-08 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20211108_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.UUID('53268a22-d111-4dd9-86aa-2c790667de9c'), editable=False, unique=True),
        ),
    ]
