# Generated by Django 3.1.7 on 2021-11-10 ~:~

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20211108_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
