# Generated by Django 3.1.7 on 2021-11-10 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
