# Generated by Django 3.1.7 on 2021-11-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20211110_1724'),
        ('subscriptions', '0014_remove_uuid_null'),
    ]

    operations = [
    ]
