# Generated by Django 3.1.7 on 2021-11-10 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hashid',
            field=models.UUIDField(default=uuid.UUID('50f1145a-20b4-4f77-941d-dac627c995e1'), editable=False, unique=True),
        ),
    ]
