# Generated by Django 3.1.7 on 2021-07-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
